name:                linear-code
version:             0.1.0.0
github:              "wchresta/linear-code"
license:             BSD3
author:              "Wanja Chresta"
maintainer:          "wanja.hs@chrummibei.ch"
copyright:           "2018, Wanja Chresta"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A simple library for linear codes (coding theory, error correction)
category:            Mathematics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wchresta/linear-code#readme>

dependencies:
    - base >= 4.7 && < 5
    - matrix >= 0.3
    - modular-arithmetic >= 1.2
    #- hmatrix >= 0.18
    #- array >= 0.5
    - reflection >= 2.1
    #- comonad
    #- profunctors

library:
  source-dirs: src
  exposed-modules:
    - Numeric.Field.Finite
    - Numeric.Code.Linear

tests:
  linear-code-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - linear-code
    - tasty
    - tasty-smallcheck
    - tasty-hunit
    - smallcheck

github: wchresta/linear-code
