name:                linear-code
version:             0.1.0.0
github:              "wchresta/linear-code"
license:             GPL3
author:              "Wanja Chresta"
maintainer:          "wanja.hs@chrummibei.ch"
copyright:           "2018, Wanja Chresta"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis: A simple library for linear codes (coding theory, error correction)
category: Mathematics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/wchresta/linear-code#readme>

dependencies:
    - base >= 4.7 && < 5
    - combinat >= 0.2
    - containers >= 0.5
    - data-default >= 0.5
    - matrix >= 0.3
    - HaskellForMaths >= 0.4
    - ghc-typelits-natnormalise >= 0.2
    - ghc-typelits-knownnat >= 0.4
    - random
    - MonadRandom
      #   - hmatrix
      #   - polynomial

library:
  source-dirs: src
  exposed-modules:
    - Math.Algebra.Code.Linear
    - Math.Algebra.Field.Instances
    - Math.Algebra.Field.Static
    - Math.Algebra.Matrix

tests:
  linear-code-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - linear-code
    - tasty
    - tasty-smallcheck
    - tasty-quickcheck
    - tasty-hunit
    - QuickCheck
    - smallcheck

github: wchresta/linear-code
