name:                linear-code
version:             0.1.1
github:              "wchresta/linear-code"
license:             GPL-3
author:              "Wanja Chresta"
maintainer:          "wanja dot hs at chrummibei dot ch"
copyright:           "2018, Wanja Chresta"

extra-source-files:
- ChangeLog.md
- README.md

# Metadata used when publishing your package
synopsis: A simple library for linear codes (coding theory, error correction)
category: Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/wchresta/linear-code#readme>

dependencies:
    - base >= 4.7 && < 5
    - containers
    - data-default
    - matrix
    - HaskellForMaths
    - ghc-typelits-natnormalise
    - ghc-typelits-knownnat
    - random
    - random-shuffle

library:
  source-dirs: src
  exposed-modules:
    - Math.Algebra.Code.Linear
    - Math.Algebra.Field.Instances
    - Math.Algebra.Field.Static
    - Math.Algebra.Matrix
  ghc-options:
    - -Wall

tests:
  linear-code-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - linear-code
    - tasty
    - tasty-smallcheck
    - tasty-quickcheck
    - tasty-hunit
    - QuickCheck
    - smallcheck

github: wchresta/linear-code
